github: [hxtree]
<<<<<<< HEAD
patreon: octocat
tidelift: npm/octo-package
custom: ["https://www.paypal.me/octocat", octocat.com]
=======
custom: ["https://www.paypal.me/hxtree", hxtree]
>>>>>>> 83f7a73fbda29ffff4a1d14db44df18f67c299e1
