language: php

branches:
  only:
    - master

php:
  - 7.3
  - 7.4

env:
  global:
    - LOG_DIR=build/logs

before_install:

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - composer clear
  - composer install --no-scripts -vvv

jobs:
  include:
    - stage: Test
      script:
        - bash <(curl -s https://codecov.io/bash)