language: php

branches:
  only:
    - master

php:
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    - LOG_DIR=build/logs

before_install:

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - composer clear
  - composer install --no-scripts --no-dev -vvv

jobs:
  include:
    - stage: Test
      script:
        - mkdir -p build/logs
        - phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
      after_script:
        - bash <(curl -s https://codecov.io/bash)