language: php

branches:
  only:
    - master

php:
  - 7.3
  - 7.4

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - stage: Test
      install:
        - composer install
        - composer update --no-scripts
      script:
        - mkdir -p build/logs
        - phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
      after_script:
        - bash <(curl -s https://codecov.io/bash)