language: php

branches:
  only:
    - master

php:
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - stage: Test
      install:
        - composer install
      script:
        - $TRAVIS_BUILD_DIR/vendor/bin/phpunit
        - mkdir -p build/logs
        - phpunit --coverage-clover build/logs/clover.xml
      after_script:
        - bash <(curl -s https://codecov.io/bash)