language: php

branches:
  only:
    - master

php:
  - 7.3
  - 7.4

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
  - composer install
  - composer self-update --no-scripts

jobs:
  include:
    - stage: Test
      script:
        - mkdir -p build/logs
        - phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
      after_script:
        - bash <(curl -s https://codecov.io/bash)