coverage:
  status:
    project:
      default:
        target: 90%
      src:
        target: 100%
        flags:
          - src

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null
flags:
  src:
    paths:
      - build/logs/clover.xml
    carryforward: false