#
# Component Config
#
version: 1
components:
  directory: '/src/Components'
  # type of components to instantiate
  types:
    - name: 'Block'
      class_name: 'LivingMarkup\Component\Blocks\{name}'
      xpath: '//block'
    - name: 'Partial'
      class_name: 'LivingMarkup\Component\Partials\{name}'
      xpath: '//partial'
    - name: 'Widget'
      class_name: 'LivingMarkup\Component\Widgets\{name}'
      xpath: '//widget'
    - name: 'Images'
      xpath: '//img'
      class_name: 'LivingMarkup\Component\Img'
    - name: 'Link'
      xpath: '//a'
      class_name: 'LivingMarkup\Component\A'
    - name: 'Variable'
      xpath: '//var'
      class_name: 'LivingMarkup\Component\Variable'
    - name: 'If Statement'
      xpath: '//if'
      class_name: 'LivingMarkup\Component\IfStatement'
    - name: 'Redact'
      xpath: '//redact'
      class_name: 'LivingMarkup\Component\Redact'

  # order determines execution
  methods:
    - name: 'beforeLoad'
      descirption: 'Execute before object data load'
    - name: 'onLoad'
      descirption: 'Execute during object data load'
    - name: 'afterLoad'
      description: 'Execute after object data loaded'
    - name: 'beforeRender'
      description: 'Execute before object render'
    - name: 'onRender'
      description: 'Execute during object render'
      execute: 'RETURN_CALL'
    - name: 'afterRender'
      descirption: 'Execute after object rendered'