# ./docker-compose.dev.yml

version: '3'

services:

  webapp:
    volumes:
       - "/var/www/hxtree/livingmarkup/:/var/www"

#  db:
#    volumes:
#      - "./volumes/mysql_dev:/var/lib/mysql"
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=db_dev
#      - MYSQL_USER=dbuser
#      - MYSQL_PASSWORD=dbpassword
#    ports:
#      - 33061:3306
