#
# Component Config
#
version: 1
modules:
  types:
    - name: 'Image'
      xpath: '//img'
      class_name: 'LivingMarkup\Modules\Core\Image'
    - name: 'Hyperlink'
      xpath: '//a'
      class_name: 'LivingMarkup\Modules\Core\Hyperlink'
    - name: 'Variable'
      xpath: '//var'
      class_name: 'LivingMarkup\Modules\Core\Variable'
    - name: 'If Statement'
      xpath: '//if'
      class_name: 'LivingMarkup\Modules\Core\IfStatement'
    - name: 'Redact'
      xpath: '//redact'
      class_name: 'LivingMarkup\Modules\Core\Redact'
    - name: 'Block'
      class_name: 'LivingMarkup\Modules\Custom\Blocks\{name}'
      xpath: '//block'
      settings:
        - cache_duration: '1 hour'
        - search_index: false
    - name: 'Partial'
      class_name: 'LivingMarkup\Modules\Custom\Partials\{name}'
      xpath: '//partial'
    - name: 'Widget'
      class_name: 'LivingMarkup\Modules\Custom\Widgets\{name}'
      xpath: '//widget'

  methods:
    - name: 'beforeLoad'
      descirption: 'Execute before object data load'
    - name: 'onLoad'
      descirption: 'Execute during object data load'
    - name: 'afterLoad'
      description: 'Execute after object data loaded'
    - name: 'beforeRender'
      description: 'Execute before object render'
    - name: 'onRender'
      description: 'Execute during object render'
      execute: 'RETURN_CALL'
    - name: 'afterRender'
      descirption: 'Execute after object rendered'