#
# Component Config
#
version: 1
modules:
  # consider not in xpath as to avoid parsing user data by adding [not(ancestor::X)]
  # parse these modules
  types:
    - name: 'Code'
      xpath: '//code'
      class_name: 'LivingMarkup\Modules\Core\Code'
    - name: 'If Statement'
      xpath: '//if[not(ancestor::code)]'
      class_name: 'LivingMarkup\Modules\Core\IfStatement'
    - name: 'Variable'
      xpath: '//var[not(ancestor::code)]'
      class_name: 'LivingMarkup\Modules\Core\Variable'
    - name: 'Image'
      xpath: '//img[not(ancestor::code)]'
      class_name: 'LivingMarkup\Modules\Core\Image'
    - name: 'Hyperlink'
      xpath: '//a[not(ancestor::code)]'
      class_name: 'LivingMarkup\Modules\Core\Hyperlink'
    - name: 'Redact[not(ancestor::code)]'
      xpath: '//redact'
      class_name: 'LivingMarkup\Modules\Core\Redact'
    - name: 'Block[not(ancestor::code)]'
      class_name: 'LivingMarkup\Modules\Custom\Blocks\{name}'
      xpath: '//block[not(ancestor::code)]'
      settings:
        - cache_duration: '1 hour'
        - search_index: false
    - name: 'Partial'
      class_name: 'LivingMarkup\Modules\Custom\Partials\{name}'
      xpath: '//partial[not(ancestor::code)]'
    - name: 'Widget'
      class_name: 'LivingMarkup\Modules\Custom\Widgets\{name}'
      xpath: '//widget[not(ancestor::code)]'
  # auto call these methods
  methods:
    - name: 'beforeLoad'
      descirption: 'Execute before object data load'
    - name: 'onLoad'
      descirption: 'Execute during object data load'
    - name: 'afterLoad'
      description: 'Execute after object data loaded'
    - name: 'beforeRender'
      description: 'Execute before object render'
    - name: 'onRender'
      description: 'Execute during object render'
      execute: 'RETURN_CALL'
    - name: 'afterRender'
      descirption: 'Execute after object rendered'