#
# Component Config
#
version: 1
modules:
  # skip processing element with ancestor set to false by using:
  # xpath: "//element[not(ancestor::*[@process='false'])]"
  types:
    - name: 'Code'
      xpath: "//code[not(ancestor::*[@process='false'])]"
      class_name: 'LivingMarkup\Modules\Core\Code'
    - name: 'If Statement'
      xpath: "//if[not(ancestor::*[@process='false'])]"
      class_name: 'LivingMarkup\Modules\Core\IfStatement'
    - name: 'Variable'
      xpath: "//var[not(ancestor::*[@process='false'])]"
      class_name: 'LivingMarkup\Modules\Core\Variable'
    - name: 'Image'
      xpath: "//img[not(ancestor::*[@process='false'])]"
      class_name: 'LivingMarkup\Modules\Core\Image'
    - name: 'Hyperlink'
      xpath: "//a[not(ancestor::*[@process='false'])]"
      class_name: 'LivingMarkup\Modules\Core\Hyperlink'
    - name: 'Redact'
      xpath: "//redact[not(ancestor::*[@process='false'])]"
      class_name: 'LivingMarkup\Modules\Core\Redact'
    - name: "Block[not(ancestor::*[@process='false'])]"
      class_name: 'LivingMarkup\Modules\Custom\Blocks\{name}'
      xpath: "//block[not(ancestor::*[@process='false'])]"
      settings:
        - cache_duration: '1 hour'
        - search_index: false
    - name: 'Partial'
      class_name: 'LivingMarkup\Modules\Custom\Partials\{name}'
      xpath: "//partial[not(ancestor::*[@process='false'])]"
    - name: 'Widget'
      class_name: 'LivingMarkup\Modules\Custom\Widgets\{name}'
      xpath: "//widget[not(ancestor::*[@process='false'])]"
  # auto call these methods
  methods:
    - name: 'beforeLoad'
      descirption: 'Execute before object data load'
    - name: 'onLoad'
      descirption: 'Execute during object data load'
    - name: 'afterLoad'
      description: 'Execute after object data loaded'
    - name: 'beforeRender'
      description: 'Execute before object render'
    - name: 'onRender'
      description: 'Execute during object render'
      execute: 'RETURN_CALL'
    - name: 'afterRender'
      descirption: 'Execute after object rendered'